import { readFileSync } from 'fs';
const d = JSON.parse(readFileSync('./data/providers.json','utf8'));
console.log("Total providers:", d.providers.length);
console.log("Custody types:", d.custodyTypes.length);
const slugs = d.providers.map(p => p.slug);
const dupSlugs = slugs.filter((s, i) => slugs.indexOf(s) !== i);
console.log("Duplicate slugs:", dupSlugs.length > 0 ? dupSlugs.join(", ") : "None ✓");
const scoreKeys = ["security","insurance","regulatory","feeTransparency","trackRecord","withdrawalFlexibility","reportingAudit","counterpartyDiversification"];
let bad = 0;
d.providers.forEach(p => { scoreKeys.forEach(k => { if (typeof p.scores[k] !== 'number') { console.log("Missing " + k + " for " + p.id); bad++; } }); });
console.log("Bad scores:", bad === 0 ? "None ✓" : bad);
const typeCounts = {};
d.providers.forEach(p => { typeCounts[p.custodyType] = (typeCounts[p.custodyType] || 0) + 1; });
console.log("\nBy custody type:");
Object.entries(typeCounts).forEach(([t,c]) => console.log("  " + t + ": " + c));
const typeIds = new Set(d.custodyTypes.map(t => t.id));
const providerTypes = new Set(d.providers.map(p => p.custodyType));
const missing = [...providerTypes].filter(t => !typeIds.has(t));
console.log("\nMissing type definitions:", missing.length === 0 ? "None ✓" : missing.join(", "));
console.log("Total comparisons:", d.providers.length * (d.providers.length - 1) / 2);
